image: Visual Studio 2017

os: unstable

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm install

build_script:
  - npm run lint
  - npm run test
  - npm run test:e2e
  - npm run build

on_success:
  - ps: |
      if (($env:APPVEYOR_REPO_COMMIT_MESSAGE -Match "pubchoco") -and ($env:APPVEYOR_REPO_BRANCH -eq "master")) {
        cd pkgs/chocolatey
        [xml]$spec = Get-Content .\ipfs-desktop.nuspec
        $version=$spec.package.metadata.version
        choco pack
        choco push .\ipfs-desktop.$version.nupkg --key $env:CHOCO_KEY --source https://push.chocolatey.org
      }

test: off
